apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: app
          image: traefik/whoami:v1.11.0
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
