# Generated from github.com/metno/weathericons weather/legend.csv (MIT), commit 89e3173.
# MET Norway symbol id -> English text. The API adds _day, _night or _polartwilight to some ids.
SYMBOLS = {
    "clearsky": "Clear sky",
    "fair": "Fair",
    "partlycloudy": "Partly cloudy",
    "cloudy": "Cloudy",
    "lightrainshowers": "Light rain showers",
    "rainshowers": "Rain showers",
    "heavyrainshowers": "Heavy rain showers",
    "lightrainshowersandthunder": "Light rain showers and thunder",
    "rainshowersandthunder": "Rain showers and thunder",
    "heavyrainshowersandthunder": "Heavy rain showers and thunder",
    "lightsleetshowers": "Light sleet showers",
    "sleetshowers": "Sleet showers",
    "heavysleetshowers": "Heavy sleet showers",
    "lightssleetshowersandthunder ": "Light sleet showers and thunder",
    "sleetshowersandthunder": "Sleet showers and thunder",
    "heavysleetshowersandthunder": "Heavy sleet showers and thunder",
    "lightsnowshowers": "Light snow showers",
    "snowshowers": "Snow showers",
    "heavysnowshowers": "Heavy snow showers",
    "lightssnowshowersandthunder": "Light snow showers and thunder",
    "snowshowersandthunder": "Snow showers and thunder",
    "heavysnowshowersandthunder": "Heavy snow showers and thunder",
    "lightrain": "Light rain",
    "rain": "Rain",
    "heavyrain": "Heavy rain",
    "lightrainandthunder": "Light rain and thunder",
    "rainandthunder": "Rain and thunder",
    "heavyrainandthunder": "Heavy rain and thunder",
    "lightsleet": "Light sleet",
    "sleet": "Sleet",
    "heavysleet": "Heavy sleet",
    "lightsleetandthunder": "Light sleet and thunder",
    "sleetandthunder": "Sleet and thunder",
    "heavysleetandthunder": "Heavy sleet and thunder",
    "lightsnow": "Light snow",
    "snow": "Snow",
    "heavysnow": "Heavy snow",
    "lightsnowandthunder": "Light snow and thunder",
    "snowandthunder": "Snow and thunder",
    "heavysnowandthunder": "Heavy snow and thunder",
    "fog": "Fog",
}
