apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  # Same key names as the 2021 Bitnami chart
  mysql-root-password: {{ required "set mysql.auth.rootPassword" .Values.auth.rootPassword | b64enc | quote }}
  mysql-password: {{ required "set mysql.auth.password" .Values.auth.password | b64enc | quote }}
